w3c/performance-timeline

- index.html
Switch exception type for #19.
> AbortError => TypeError

- index.html
> Fix typedef syntax

- index.html
Fix: #15 Second example disconnects immediately which means nothing is delivered
> Fix: #15 Second example disconnects immediately

- index.html
Aligning with https://github.com/w3c/hr-time/pull/7
> Now uses HR-TIME as the basis

- index.html
> Vendor prefixes

- index.html
Initial proposal to deal with getEntries* and clear*
> Added the performance entry buffer

- index.html
> Case sensitivity for getEntries

- index.html
> add a note regarding feature detection

- index.html
Integrate feedback from #90, #91, #93, #94.
@bzbarsky ptal.
***
[Preview](https://s3.amazonaws.com/pr-preview/w3c/performance-timeline/observe-cleanup.html) | [Diff](https://s3.amazonaws.com/pr-preview/w3c/performance-timeline/74a9181...6d7e857.html)
> Improve observe() logic and references

- index.html
Closes #74.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/performance-timeline/pull/98.html" title="Last updated on Dec 8, 2017, 10:37 PM GMT (9154b82)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/performance-timeline/98/43cf7a3...9154b82.html" title="Last updated on Dec 8, 2017, 10:37 PM GMT (9154b82)">Diff</a>
> define PerformanceObserver#takeRecords()

- index.html
***
<a href="https://pr-preview.s3.amazonaws.com/foolip/performance-timeline/pull/102.html" title="Last updated on Jun 12, 2018, 8:48 AM GMT (42da51a)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/performance-timeline/102/aecfdf4...foolip:42da51a.html" title="Last updated on Jun 12, 2018, 8:48 AM GMT (42da51a)">Diff</a>
> Update web-platform-tests URL

- index.html
Closes #106
***
<a href="https://pr-preview.s3.amazonaws.com/yoavweiss/performance-timeline/pull/107.html" title="Last updated on Oct 9, 2018, 11:28 AM GMT (14ac04e)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/performance-timeline/107/81a6242...yoavweiss:14ac04e.html" title="Last updated on Oct 9, 2018, 11:28 AM GMT (14ac04e)">Diff</a>
> Remove dependencies section

- index.html
https://github.com/w3c/performance-timeline/issues/81
***
<a href="https://pr-preview.s3.amazonaws.com/ehanley324/performance-timeline/pull/123.html" title="Last updated on May 9, 2019, 3:06 PM UTC (04441b7)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/performance-timeline/123/58b1f72...ehanley324:04441b7.html" title="Last updated on May 9, 2019, 3:06 PM UTC (04441b7)">Diff</a>
> Buffered flag spec changes

- .travis.yml
> terminate auto-pub on gh-pages

- index.html
Fixes https://github.com/w3c/performance-timeline/issues/117
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/performance-timeline/pull/134.html" title="Last updated on Jun 13, 2019, 12:15 AM UTC (f9cc9f1)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/performance-timeline/134/f52954d...f9cc9f1.html" title="Last updated on Jun 13, 2019, 12:15 AM UTC (f9cc9f1)">Diff</a>
> Merge using registry to L2

- index.html
Makes writing easier
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/performance-timeline/pull/132.html" title="Last updated on Jun 24, 2019, 7:38 PM UTC (1c55d09)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/performance-timeline/132/9fcb9a4...1c55d09.html" title="Last updated on Jun 24, 2019, 7:38 PM UTC (1c55d09)">Diff</a>
> References cleanup

- .travis.yml
- W3CTRMANIFEST
To fix #124 . 
To set up auto-pub based on the level2 branch.
***
<a href="https://pr-preview.s3.amazonaws.com/siusin/performance-timeline/pull/127.html" title="Last updated on Jun 26, 2019, 7:43 PM UTC (f13c030)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/performance-timeline/127/c1aef83...siusin:f13c030.html" title="Last updated on Jun 26, 2019, 7:43 PM UTC (f13c030)">Diff</a>
> Auto pub level2

- index.html
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/performance-timeline/pull/151.html" title="Last updated on Sep 15, 2019, 9:06 AM UTC (22b6c6f)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/performance-timeline/151/208221f...22b6c6f.html" title="Last updated on Sep 15, 2019, 9:06 AM UTC (22b6c6f)">Diff</a>
> editorial: fix ReSpec warnings

- index.html
https://github.com/w3c/performance-timeline/issues/160
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/performance-timeline/pull/161.html" title="Last updated on Feb 19, 2020, 4:18 PM UTC (a18385a)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/performance-timeline/161/c01ade4...a18385a.html" title="Last updated on Feb 19, 2020, 4:18 PM UTC (a18385a)">Diff</a>
> Clear options list upon call to disconnect

- w3c.json
> w3c.json tweaks

- index.html
change in respec config 
+ wording in intro
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/performance-timeline/pull/204.html" title="Last updated on Nov 10, 2022, 8:44 PM UTC (e1b67dc)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/performance-timeline/204/925ae5e...e1b67dc.html" title="Last updated on Nov 10, 2022, 8:44 PM UTC (e1b67dc)">Diff</a>
> Removing mentions of "level 2"

- index.html
***
<a href="https://pr-preview.s3.amazonaws.com/Elchi3/performance-timeline/pull/205.html" title="Last updated on Nov 15, 2022, 5:20 PM UTC (7ae823b)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/performance-timeline/205/4b589a7...Elchi3:7ae823b.html" title="Last updated on Nov 15, 2022, 5:20 PM UTC (7ae823b)">Diff</a>
> Fix stray ">"
