w3c/performance-timeline

index.html

- Moves definition of Performance interface from NavTiming into Performance Timeline (NavTiming update will be handled in a separate changeset).
- Performance interface is exposed to [Window, Worker].
- Other editorial cleanup.
@plehegar: can you take a quick pass?
Closes #6.

Define Performance interface

---

index.html

**Note: this is a WIP pull... expect more commits to land as we iterate on this.**
Preview: https://rawgit.com/w3c/performance-timeline/performanceobserver/index.html
---
* Defines [PerformanceObserver interface](https://rawgit.com/w3c/performance-timeline/performanceobserver/index.html#the-performanceobserver-interface) 
* Inspired by [Mutation Observers](http://www.w3.org/TR/dom/#mutation-observers) and can be used to subscribe to / observe new performance events delivered into the Performance Timeline. 
* Creating a subscription requires that you provide a list of entryTypes that you want to listen for.
* Defines [LazyPerformanceEntryList interface](https://rawgit.com/w3c/performance-timeline/performanceobserver/index.html#the-lazyperformanceentrylist-interface) 
* Provides getEntries, …

PerformanceObserver

---

index.html

See issue #17 
Change the name from LazyPerformanceEntryList to PerformanceObserverEntries.

Changed parameter name to remove 'Lazy'

---

index.html

Preview: https://rawgit.com/w3c/performance-timeline/getEntries-filter/index.html#methods
For background and context, see: https://github.com/w3c/performance-timeline/pull/9#issuecomment-89042906. 
- getEntries() returns copy of all items (as before)
- (new) getEntries(optional dictionary):
-- allows attribute queries against PerformanceEntry objects
- getEntriesByType(type) -> getEntries({'entryType': type})
- getEntriesByName(name) -> getEntries({'name': name})
- getEntriesByName(name, type) -> getEntries({'name': name, 'entryType':
type})

Extend getEntries to allow attribute filtering

---

index.html

Change PerformanceObserver from using a constructor to using performance.createPerformanceObserver.
This pull request replaces #29.

Change PerformanceObserver from using a constructor to using Performance interface.

---

index.html

This is a followup to discussion in https://github.com/w3c/performance-timeline/pull/29#issuecomment-119754195. 
- defined entryType enum with links to appropriate specs/interfaces
- changed method signatures to use PerformanceEntryType enum
- changed typeFilter -> entryType to be consistent with getEntriesBy*
Preview: https://rawgit.com/w3c/performance-timeline/entryType/index.html#the-performanceentry-interface

entryType enum + consistent use

---

index.html

As per #40, revert from window.performance.createPerformanceObserver to using new PerformanceObserver

Revert to using a constructor for PerformanceObserver.

---

index.html

Preview: https://rawgit.com/w3c/performance-timeline/processing/index.html#performance-timeline
- Provides a "queue a PerformanceEntry" hook for other specifications.
- Defines steps for delivering events to observers.
- Defines task to trigger application callbacks for observers with buffered entries.
The rough algorithm is as follows: events are queued by various subsystems and delivered into each observer's buffer; when an event is queued, a task is created to trigger application callback on relevant observers; the task iterates over all registered observers and dispatches application callbacks for observers that have buffered events.

Processing algorithm for PerformanceObserver

---

index.html

Preview: https://rawgit.com/w3c/performance-timeline/register/index.html#the-performance-observer-interface
- each unit of related similar-origin browsing contexts' keeps a list of
registered performance observer objects
- observe(options) appends the context object (observer) to the
above list
- disconnect removes the context object (observer) from the above list
When delivering new events perf observer iterates over the above list
and dispatches new events to each observer.
Closes #44

Clarify perf observer registration process

---

index.html

The previous phrasing made it sound as though only performance timeline entries which the user agent is responsible for recording are observable. It might be better to make this more explicit than what I've proposed, but I think this is less confusing than what was there before.

Observers observe user timing entries.

---

index.html

Adds some additional context for why PerfObserver interface was added,
what problems it addresses, and why it should be the preferred method to
access the Performance Timeline moving forward.
---
Context: [TAG feedback](https://github.com/w3ctag/spec-reviews/issues/18#issuecomment-206523833)
/cc @toddreifsteck @plehegar @yoavweiss

Explain why PerfObserver in the introduction

---

index.html

Background: https://github.com/w3c/performance-timeline/issues/57#issuecomment-248292074. Closes https://github.com/w3c/performance-timeline/issues/60.
Preview: https://cdn.rawgit.com/w3c/performance-timeline/remove-filteroptions/index.html

remove PerformanceEntryFilterOptions

---

index.html

* Fix the [Markup errors](https://validator.w3.org/nu/?doc=https%3A%2F%2Fw3c.github.io%2Fperformance-timeline%2F) reported by the validator. ReSpec now recommends using [data-dfn-for](https://github.com/w3c/respec/wiki/data-dfn-for) instead of "for". 
* There seems to be a duplicated "entryType" in line 404.

fix Markup errors

---

index.html

A whole bunch of editorial + cleanup updates. No functional changes.     
- Builds on https://github.com/w3c/performance-timeline/pull/72#issuecomment-283581201.
- Moved filter method into processing
- Made filter method take a buffer
- Updated ObserverEntryList definitions to call filter method
- More logical order to the sections
- tidy formatted
The diff is scary looking, but mostly due to tidy (re)formatting. Take a look at the preview instead:
https://cdn.rawgit.com/w3c/performance-timeline/b816729b692fb136a3f12957ac298d9c5652311b/index.html

Refactor, shuffle order, improve navigation

---

index.html

* Addresses ReSpec Warnings
* Adds a bit more structure to the document
* remove invalid for= attributes
* modernize examples (tested in Chrome!)
* fix references
* tidy
@igrigorik, you will need to define `PerformanceObserverEntryList `'s methods - I've put the skeleton in place to do that. You can just say there that they work the same as `Performance`'s methods when called. You should also add sections for other interfaces and their methods and attributes. I've done a few for you already.

Fixup: ReSpec warnings, structure, etc.

---

index.html

@yoavweiss @igrigorik
***
[Preview](https://s3.amazonaws.com/pr-preview/cvazac/performance-timeline/gh-pages.html) | [Diff](https://s3.amazonaws.com/pr-preview/w3c/performance-timeline/fb07e4c...cvazac:1205c9f.html)

`PerformanceObserverInit.buffered` and `add to performance entry buffer` flags

---

index.html

***
[Preview](https://s3.amazonaws.com/pr-preview/cvazac/performance-timeline/gh-pages.html) | [Diff](https://s3.amazonaws.com/pr-preview/w3c/performance-timeline/d1f1214...cvazac:e90f4ba.html)

the `buffered` part of the processing algorithm needs to move above the potential short-circuit

---

index.html

This is a proposed fix for #87
***
[Preview](https://s3.amazonaws.com/pr-preview/w3c/performance-timeline/perf-timeline/observe/typeerr.html) | [Diff](https://s3.amazonaws.com/pr-preview/w3c/performance-timeline/ec04827...4e15343.html)

observing an empty sequence of entryTypes is a no-op

---

index.html

https://github.com/w3c/performance-timeline/pull/107 broke a couple of links. This fixes them.
/cc @npm1
***
<a href="https://pr-preview.s3.amazonaws.com/yoavweiss/performance-timeline/pull/109.html" title="Last updated on Oct 10, 2018, 8:33 PM GMT (b64fc35)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/performance-timeline/109/df33799...yoavweiss:b64fc35.html" title="Last updated on Oct 10, 2018, 8:33 PM GMT (b64fc35)">Diff</a>

Fix links after dependency removal

---

CODE_OF_CONDUCT.md
index.html

Add supportedEntryTypes and include an example of how it would be used. Solves https://github.com/w3c/performance-timeline/issues/77
***
<a href="https://pr-preview.s3.amazonaws.com/npm1/performance-timeline/pull/108.html" title="Last updated on Nov 26, 2018, 5:00 PM GMT (7e93eeb)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/performance-timeline/108/09c9d0a...npm1:7e93eeb.html" title="Last updated on Nov 26, 2018, 5:00 PM GMT (7e93eeb)">Diff</a>

Define supportedEntryTypes

---

index.html

This change introduces a DOMString type in PerformanceObserverInit to support observing a single entryType with other parameters from the dictionary. The change modifies the observe() method so that:
* observe({entryTypes:...}) is still supported but not with any other member of the PerformanceObserverInit dictionary.
* observe({type: ...}) is now supported, and multiple calls stack.
* Both ways to call observe() cannot be mixed. That is, an observer has to stick to one of the ways, and 'observer type' is introduced to enforce this.
In addition, some nits are fixed along the way, such as using <var> and <a> appropriately throughout.
Solves https://github.com/w3c/performance-timeline/issues/103
***
<a href="https://pr-preview.s3.amazonaws.com/npm1/performance-timeline/pull/112.html" …

Add |type| to PerformanceObserverInit

---

index.html

This PR removes the buffered flag from the L2 branch in preparation for republishing L2.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/performance-timeline/pull/114.html" title="Last updated on Mar 15, 2019, 5:33 PM UTC (4cdff92)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/performance-timeline/114/0534f9c...4cdff92.html" title="Last updated on Mar 15, 2019, 5:33 PM UTC (4cdff92)">Diff</a>

L2: Remove buffered flag

---

index.html

It seems that the whole href has to be in a single line for the link to be used with the algorithm name.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/performance-timeline/pull/115.html" title="Last updated on Mar 20, 2019, 2:48 PM UTC (cd61fc4)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/performance-timeline/115/0534f9c...cd61fc4.html" title="Last updated on Mar 20, 2019, 2:48 PM UTC (cd61fc4)">Diff</a>

Fix a link to filter algorithm

---

index.html

***
<a href="https://pr-preview.s3.amazonaws.com/w3c/performance-timeline/pull/116.html" title="Last updated on Mar 21, 2019, 2:34 AM UTC (c102386)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/performance-timeline/116/aaad0f2...c102386.html" title="Last updated on Mar 21, 2019, 2:34 AM UTC (c102386)">Diff</a>

Fix a link to filter algorithm again

---

index.html

It seems that it must be made optional to confirm with WebIDL spec. Fortunately the observe() processing will already throw if 'entryTypes' and 'type' are both omitted (which is what would happen if the parameter is missing, as an empty dictionary is assumed), so no additional changes are required.
Solves https://github.com/w3c/performance-timeline/issues/119
@whh8b FYI
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/performance-timeline/pull/120.html" title="Last updated on Mar 28, 2019, 4:21 PM UTC (c93fbf8)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/performance-timeline/120/3139cce...c93fbf8.html" title="Last updated on Mar 28, 2019, 4:21 PM UTC (c93fbf8)">Diff</a>

Make observe() parameter an optional dictionary

---

index.html

Closes #122
***
<a href="https://pr-preview.s3.amazonaws.com/yoavweiss/performance-timeline/pull/129.html" title="Last updated on May 14, 2019, 1:51 PM UTC (eff1233)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/performance-timeline/129/09e1844...yoavweiss:eff1233.html" title="Last updated on May 14, 2019, 1:51 PM UTC (eff1233)">Diff</a>

Backport the relevant global object definition for the relevant performance entry buffer

---

index.html

Fixes https://github.com/w3c/performance-timeline/issues/113 and https://github.com/w3c/performance-timeline/issues/117
Adds 'SameObject' and FrozenArray logic that is per global object.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/performance-timeline/pull/133.html" title="Last updated on Jun 12, 2019, 11:02 PM UTC (421d5e9)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/performance-timeline/133/674369a...421d5e9.html" title="Last updated on Jun 12, 2019, 11:02 PM UTC (421d5e9)">Diff</a>

Use registry for supportedEntryTypes

---

index.html

Now that we have a global entry names registry, the map of entrytype to buffer should be initialized with values from that table.
***
<a href="https://pr-preview.s3.amazonaws.com/ehanley324/performance-timeline/pull/135.html" title="Last updated on Jun 25, 2019, 6:14 PM UTC (d2094cf)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/performance-timeline/135/def3145...ehanley324:d2094cf.html" title="Last updated on Jun 25, 2019, 6:14 PM UTC (d2094cf)">Diff</a>

Update buffer map initialization

---

index.html

Reverts the index.html change in https://github.com/w3c/performance-timeline/commit/4029b1d54d3e0dd4799ef8407b96ed9b96469567
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/performance-timeline/pull/140.html" title="Last updated on Jul 8, 2019, 2:39 PM UTC (c8af867)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/performance-timeline/140/4029b1d...c8af867.html" title="Last updated on Jul 8, 2019, 2:39 PM UTC (c8af867)">Diff</a>

Revert deletion of buffered flag

---

index.html

This PR changes the definition to take a global object as input, and changes the two callers to specify the object explicitly. Also change some variables encountered to camelCase.
Fixes https://github.com/w3c/performance-timeline/issues/130
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/performance-timeline/pull/142.html" title="Last updated on Jul 8, 2019, 7:35 PM UTC (dbee204)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/performance-timeline/142/3944da1...dbee204.html" title="Last updated on Jul 8, 2019, 7:35 PM UTC (dbee204)">Diff</a>

Fix relevant performance entry tuple usage

---

index.html

This PR adds a dfn to availableFromTimeline so that it links properly when referenced later. It changes to dfn only since there is already a link to the registry.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/performance-timeline/pull/141.html" title="Last updated on Jul 8, 2019, 8:40 PM UTC (73a6069)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/performance-timeline/141/4863a02...73a6069.html" title="Last updated on Jul 8, 2019, 8:40 PM UTC (73a6069)">Diff</a>

Fix link to availableFromTimeline

---

README.md

Currently, there is no explainer. This PR adds an explainer so that developers don't have to read the spec.

Add a basic explainer

---

index.html

Addresses the comment in https://github.com/w3c/performance-timeline/pull/142#pullrequestreview-259856252
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/performance-timeline/pull/144.html" title="Last updated on Jul 10, 2019, 9:18 PM UTC (356d904)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/performance-timeline/144/1257b48...356d904.html" title="Last updated on Jul 10, 2019, 9:18 PM UTC (356d904)">Diff</a>

Fix input ordering

---

index.html

Due to the reSpec change, the IDL is underlined in red when the default parameter is not provided.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/performance-timeline/pull/147.html" title="Last updated on Jul 24, 2019, 5:21 PM UTC (7ea4677)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/performance-timeline/147/8b7240a...7ea4677.html" title="Last updated on Jul 24, 2019, 5:21 PM UTC (7ea4677)">Diff</a>

Add default value to observe() parameter

---

index.html

This change moves the example description so it occurs before the example. It also adds description of the buffered flag.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/performance-timeline/pull/148.html" title="Last updated on Aug 19, 2019, 4:19 PM UTC (58270db)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/performance-timeline/148/a07b098...58270db.html" title="Last updated on Aug 19, 2019, 4:19 PM UTC (58270db)">Diff</a>

Add buffered flag explanation in Introduction

---

index.html

This prevents ReSpec from highlighting in red the whole WebIDL content.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/performance-timeline/pull/152.html" title="Last updated on Oct 9, 2019, 7:36 PM UTC (ebf7567)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/performance-timeline/152/d557fb0...ebf7567.html" title="Last updated on Oct 9, 2019, 7:36 PM UTC (ebf7567)">Diff</a>

L2 branch: move constructor to a method

---

index.html

The use of the infra concepts might need some improvement. I'd suggest having a look at the infra spec itself for usage. 
Also, "ECMAScript global environment" is not a defined thing (it's a section in WebIDL, sure... but it's not a defined term)... I assumed you meant the "global object" from HTML? WebIDL defers to HTML for that. Please confirm before merging - if it's not correct, please advise on a more suitable (exported) concept.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/performance-timeline/pull/154.html" title="Last updated on Oct 17, 2019, 7:30 AM UTC (23bb645)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/performance-timeline/154/714a3cc...23bb645.html" title="Last updated on Oct 17, 2019, 7:30 AM UTC (23bb645)">Diff</a>

chore: fixup some xrefs

---

index.html

Fixes https://github.com/w3c/performance-timeline/issues/153 To avoid having ReSpec red errors in WebIDL, this PR does two changes:
* Make the dictionary optional and add a default value to it (matches the master branch declaration)
* Add xref to hr-time-2 so that DOMHighResTimeStamp is found
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/performance-timeline/pull/155.html" title="Last updated on Oct 18, 2019, 3:09 PM UTC (f9242ae)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/performance-timeline/155/e247ab2...f9242ae.html" title="Last updated on Oct 18, 2019, 3:09 PM UTC (f9242ae)">Diff</a>

Level2: more ReSpec fixes

---

index.html

This led to a confusing entry in the references section that claimed to
point to the 2012 REC, but the https://www.w3.org/TR/hr-time/ URL
redirected to the 2019 PR.
***
<a href="https://pr-preview.s3.amazonaws.com/jyasskin/performance-timeline/pull/156.html" title="Last updated on Dec 6, 2019, 5:54 PM UTC (18f7beb)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/performance-timeline/156/30ddab4...jyasskin:18f7beb.html" title="Last updated on Dec 6, 2019, 5:54 PM UTC (18f7beb)">Diff</a>

Remove unused [hr-time] reference.

---

index.html

There have been some changes in markdown processing, which are incompatible with this document. Also, markdown is not used in the document, so removing it.
As an add-on, changed ReSpec script to lite jQuery-less version.
***
<a href="https://pr-preview.s3.amazonaws.com/sidvishnoi/performance-timeline/pull/157.html" title="Last updated on Dec 30, 2019, 2:11 PM UTC (dc57e33)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/performance-timeline/157/f1eb177...sidvishnoi:dc57e33.html" title="Last updated on Dec 30, 2019, 2:11 PM UTC (dc57e33)">Diff</a>

chore: fix ReSpec errors

---

index.html

Fixes https://github.com/w3c/performance-timeline/issues/158. This PR fixes observe() so that the task that dispatched PerformanceObserver callbacks is queued whenever the buffered flag is used. This lets an observer receive buffered entries even if no other entries are later queued into the performance timeline.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/performance-timeline/pull/159.html" title="Last updated on Jan 27, 2020, 4:34 PM UTC (013271a)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/performance-timeline/159/a20b0ac...013271a.html" title="Last updated on Jan 27, 2020, 4:34 PM UTC (013271a)">Diff</a>

Fix observe() with buffered flag

---

index.html

Fixes https://github.com/w3c/performance-timeline/issues/163
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/performance-timeline/pull/164.html" title="Last updated on Apr 9, 2020, 9:37 PM UTC (5fb5262)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/performance-timeline/164/87609bc...5fb5262.html" title="Last updated on Apr 9, 2020, 9:37 PM UTC (5fb5262)">Diff</a>

Do not use SyntaxError

---

index.html

This allows using the algorithm now defined in the registry before adding an entry to the observer buffer.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/performance-timeline/pull/166.html" title="Last updated on Apr 24, 2020, 5:59 PM UTC (8849a5b)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/performance-timeline/166/686b099...8849a5b.html" title="Last updated on Apr 24, 2020, 5:59 PM UTC (8849a5b)">Diff</a>

Use should add entry algorithm

---

index.html

This PR fixes https://github.com/w3c/performance-timeline/issues/167.
It does so by adding an associated list to PerformanceObserverEntryList and setting it upon construction. This way, the algorithms used in the getter methods actually make sense, as they require a raw list.
This PR also fixes a couple of links that are currently broken.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/performance-timeline/pull/170.html" title="Last updated on Jul 27, 2020, 10:11 PM UTC (503e7ab)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/performance-timeline/170/d0f77f2...503e7ab.html" title="Last updated on Jul 27, 2020, 10:11 PM UTC (503e7ab)">Diff</a>

Add entry list to PerformanceObserverEntryList

---

index.html

This PR adds a boolean that is true if and only if the observer is observing a type that has lost entries to buffering (due to a limit in the buffer size). This boolean is queried on the observer callback. Fixes https://github.com/w3c/performance-timeline/issues/169
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/performance-timeline/pull/171.html" title="Last updated on Aug 10, 2020, 3:16 PM UTC (a4f7574)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/performance-timeline/171/b7372ad...a4f7574.html" title="Last updated on Aug 10, 2020, 3:16 PM UTC (a4f7574)">Diff</a>

Add boolean unbufferedEntry to observe()

---

index.html

This PR renames the determine eligibility algorithm to a name that more clearly indicates the check done internally (checks whether the buffer is full). It also adds the shouldAdd check to right before adding the entry to the performance entry buffer, as this is now possible after https://github.com/w3c/timing-entrytypes-registry/pull/15. This is being done to allow Event Timing to only buffer entries of duration at least 104.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/performance-timeline/pull/173.html" title="Last updated on Aug 17, 2020, 6:01 PM UTC (b86efc1)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/performance-timeline/173/a075ede...b86efc1.html" title="Last updated on Aug 17, 2020, 6:01 PM UTC (b86efc1)">Diff</a>

Check shouldAdd when appending to buffer

---

index.html

This enables linking to it from other specifications. In particular this will be used in ResourceTiming for the buffer full task: https://github.com/w3c/resource-timing/issues/215
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/performance-timeline/pull/175.html" title="Last updated on Sep 15, 2020, 1:29 PM UTC (318355d)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/performance-timeline/175/24bad8b...318355d.html" title="Last updated on Sep 15, 2020, 1:29 PM UTC (318355d)">Diff</a>

Add dfn to performance timeline task source

---

index.html

This PR changes hasDroppedEntries to a dictionary containing numDroppedEntries. This is based on feedback from https://github.com/w3ctag/design-reviews/issues/547. It also fixes some ReSpec errors.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/performance-timeline/pull/177.html" title="Last updated on Mar 15, 2021, 6:21 PM UTC (020a420)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/performance-timeline/177/5ed1dd5...020a420.html" title="Last updated on Mar 15, 2021, 6:21 PM UTC (020a420)">Diff</a>

Change hasDroppedEntries to droppedEntriesCount

---

index.html

Fixes https://github.com/w3c/performance-timeline/issues/181
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/performance-timeline/pull/187.html" title="Last updated on Aug 18, 2021, 10:51 PM UTC (deeb36e)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/performance-timeline/187/acb771c...deeb36e.html" title="Last updated on Aug 18, 2021, 10:51 PM UTC (deeb36e)">Diff</a>

Update dropped entries count processing logic

---

index.html

https://github.com/w3c/performance-timeline/issues/189
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/performance-timeline/pull/190.html" title="Last updated on Sep 10, 2021, 9:29 PM UTC (4929ebb)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/performance-timeline/190/7464cc3...4929ebb.html" title="Last updated on Sep 10, 2021, 9:29 PM UTC (4929ebb)">Diff</a>

Update HR-Time links

---

index.html

This PR adds some export and applies some fixes for current warnings. When digging into https://github.com/WICG/element-timing/issues/67, I notice that some PerformanceTimeline objects are being manually imported. But this includes some IDL objects. I suspect I shouldn't have to do this?
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/performance-timeline/pull/197.html" title="Last updated on Jan 28, 2022, 2:46 PM UTC (5d5f115)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/performance-timeline/197/ef65cde...5d5f115.html" title="Last updated on Jan 28, 2022, 2:46 PM UTC (5d5f115)">Diff</a>

Add some exports used elsewhere

---

index.html

Fixes https://github.com/w3c/performance-timeline/issues/196
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/performance-timeline/pull/198.html" title="Last updated on Jan 31, 2022, 1:15 PM UTC (68a7339)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/performance-timeline/198/d1a88bf...68a7339.html" title="Last updated on Jan 31, 2022, 1:15 PM UTC (68a7339)">Diff</a>

Export performance entry buffer

---

explainer.md
index.html

This adds the concept of a `current navigation id` to the global object, which starts at 0 and is incremented on every navigation event during a page's lifetime. This navigation id then gets exposed on PerformanceEntry objects, to allow those timeline entries to be segmented by user interaction.
***
<a href="https://pr-preview.s3.amazonaws.com/clelland/performance-timeline/pull/192.html" title="Last updated on Nov 26, 2021, 5:37 PM UTC (6e5497e)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/performance-timeline/192/ca6936d...clelland:6e5497e.html" title="Last updated on Nov 26, 2021, 5:37 PM UTC (6e5497e)">Diff</a>
***
<a href="https://pr-preview.s3.amazonaws.com/clelland/performance-timeline/pull/192.html" title="Last updated on Oct 11, 2023, 3:33 PM UTC …

Add navigationId to PerformanceEntry

---

index.html

This reflects changes in Web IDL and HTML's exception reporting. See https://github.com/whatwg/html/issues/10516.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/performance-timeline/pull/220.html" title="Last updated on May 21, 2025, 7:45 AM UTC (55064b5)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/performance-timeline/220/4c985c1...55064b5.html" title="Last updated on May 21, 2025, 7:45 AM UTC (55064b5)">Diff</a>

Use "invoke" properly
